/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package remote.access.tool;

import java.util.Scanner;
import java.io.*;

public class App {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        System.out.print("Enter the Number of Seconds: ");
        int sec = 0;
        if (scan.hasNext())
            sec = scan.nextInt();
        scan.close();
        Runtime r = Runtime.getRuntime();
        try {
            System.out.println("The PC will get restarted after " + sec + " seconds.");
            r.exec("shutdown -r -t " + sec);
        } catch (IOException e) {
            System.out.println("Exception: " + e);
        }
    }
}
